name: modular_beyond
description: Smart project structure with dependency injection and route management
homepage: https://github.com/Flutterando/modular

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  melos: ^3.0.1
